name: Codacy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:${{ matrix.mysql-version }}
        env:
          MYSQL_ROOT_PASSWORD: uvlhub_root_password
          MYSQL_DATABASE: uvlhubdb_test
          MYSQL_USER: uvlhub_user
          MYSQL_PASSWORD: uvlhub_password
        ports:
          - 3306:3306
        options: >
          --health-cmd="mysqladmin ping" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
        mysql-version: ['5.7', '8.0']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Security audit with pip-audit
      run: |
        pip install pip-audit
        pip-audit || true

    - name: Run tests and generate coverage report
      run: |
        pip install codacy-coverage
        coverage run -m pytest app/modules/ --ignore-glob='*selenium*'
        coverage xml
      env:
        FLASK_ENV: testing
        MYSQL_HOSTNAME: 127.0.0.1
        MYSQL_PORT: 3306
        MYSQL_DATABASE: uvlhubdb_test
        MYSQL_USER: uvlhub_user
        MYSQL_PASSWORD: uvlhub_password

    - name: Upload coverage file as artifact
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage.xml

  cobertura:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Download coverage file
      uses: actions/download-artifact@v3
      with:
        name: coverage-report

    - name: Upload coverage to Codacy
      run: |
        pip install codacy-coverage
        python-codacy-coverage -r coverage.xml
      env:
        CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
