name: Modules Release Automation

on:
  push:
    tags:
      - 'vmodules-*' # Se ejecutará para tags que comiencen con "vmodules-"

jobs:
  release:
    name: Create Modules Release
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for modules
      run: |
        pytest app/modules

    - name: Package modules artifacts
      run: |
        tar -czf modules-artifacts.tar.gz app/modules

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Modules Release ${{ github.ref_name }}
        body: |
          This release contains artifacts for the modules directory.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upl
