name: Modules Release

on:
  push:
    tags:
      - 'vmodules-*' # Se ejecutará cuando un tag que empiece con "vmodules-" sea creado (por ejemplo, vmodules-1.0.0)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests for modules
      run: |
        pytest app/modules
        echo "Tests completed successfully."

    - name: Package modules artifacts
      run: |
        tar -czf modules-artifacts.tar.gz app/modules
        echo "Modules artifacts packaged."

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Modules Release ${{ github.ref_name }}
        body: |
          This release contains artifacts for the `modules` directory.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: modules-artifacts.tar.gz
        asset_name: modules-artifacts.tar.gz
        asset_content_type: application/gzip
